### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by kmsimproject** [remelic/AI-Chat-Bot#1]
what Licence? MIT? CC0?

**Comment by remelic** [comment]
Hi there,


MIT. If you want to use this for profit you are free to do so as far as I'm
concerned.
I'm not sure what the individual licences for the libraries are though.
If you want me to update the description I will be happy to do that as this
was mostly a hobby project.
Also if you need more details I will be happy to provide them.


Sincerely,

Peter S.

**Comment by kmsimproject** [comment]
thx reply :D
